# ===========================================
# Pre-commit Configuration für LLM-Frontend
# ===========================================
# Installation: pip install pre-commit
# Setup: pre-commit install

repos:
  # Python Code Quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python - Black Code Formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^(backend-core|auth-service|payment-service|llm-proxy|rag-service)/.*\.py$

  # Python - isort Import Sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(backend-core|auth-service|payment-service|llm-proxy|rag-service)/.*\.py$
        args: [--profile=black]

  # Python - flake8 Linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^(backend-core|auth-service|payment-service|llm-proxy|rag-service)/.*\.py$
        args: [--config=.flake8]

  # Python - bandit Security Linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^(backend-core|auth-service|payment-service|llm-proxy|rag-service)/.*\.py$
        args: [--config=.bandit]

  # JavaScript/TypeScript - Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|md|yaml|yml)$
        exclude: ^(package-lock\.json|.*\.min\.js)$

  # JavaScript/TypeScript - ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^(node_modules|dist|build)/.*$
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-prettier@9.1.0
          - eslint-plugin-prettier@5.1.3

  # Docker - Hadolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: Dockerfile.*

  # YAML - yamllint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        args: [--config-file=.yamllint]

  # SQL - sqlfluff
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.2
    hooks:
      - id: sqlfluff-lint
        files: \.sql$
        args: [--dialect=postgres]

  # Markdown - markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: [--config=.markdownlint.json]

  # Secrets Detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline=.secrets.baseline]

# Global excludes
exclude: |
  (?x)^(
    .*\.min\.(js|css)|
    .*\.lock$|
    .*/node_modules/.*|
    .*/dist/.*|
    .*/build/.*|
    .*/__pycache__/.*|
    .*\.pyc$|
    .*/logs/.*|
    .*/coverage/.*
  )$ 