version: '3.8'

# Development-spezifische Services und Overrides
services:
  # pgAdmin für Datenbank-Management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@localhost}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    profiles:
      - dev-tools

  # Mailhog für Email-Testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - app-network
    profiles:
      - dev-tools

  # Redis Commander für Redis-Management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis
    profiles:
      - dev-tools

  # Qdrant Dashboard (Web UI)
  qdrant-dashboard:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6334"  # Web UI port
    networks:
      - app-network
    depends_on:
      - vectordb
    profiles:
      - dev-tools

  # Nginx für lokale Entwicklung (optional)
  nginx-dev:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - api-gateway
      - frontend
    profiles:
      - nginx

  # Jupyter Notebook für Data Science/ML (optional)
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-dev-token}
    networks:
      - app-network
    profiles:
      - ml-tools

volumes:
  pgadmin_data:

networks:
  app-network:
    external: true 